### ISSUE TITLE
Suggestion:  Enhancement to 'Align' Function

### ISSUE THREAD

**Issue by edpalmer42** [RHWorkshop/IR-Blue-Android#1]
In the align function, include the ability to rotate the thermal image in 90 degree increments.  This will increase flexibility in the orientation of the camera and IR-Blue as well as making the app more 'tablet friendly'.

**Comment by AndyRawson** [comment]
Added to feature requests list.

**Comment by mardaso** [comment]
In Version 0.78 I added an orientation setting.
In that way you can change left to right and high to low.
Let me know if that will do.

**Comment by edpalmer42** [comment]
I think that's okay.  I'll have to wait until I've got the hardware to test it.
