### ISSUE TITLE
Nexus 4 rebooting

### ISSUE THREAD

**Issue by mkubik** [RHWorkshop/IR-Blue-Android#3]
Hi,

I just received my IR sensor hardware today, and got it up and running in no time. However, I had a few reboots of my Nexus 4 when using the Sensor app but I couldn't pinpoint this to a specific action. I usually add the crosshair cursor but that's about it.  Sometimes it happens when pressing the RUN button, sometimes just when doing nothing.But that may be just purely random. I do have the latest app installed.

:-) I just managed to crash the phone by moving the color slider at the bottom of the screen.

Any advice you can give?

Thanks!

Matthias

**Comment by mkubik** [comment]
Forgot to mention: It's a Nexus 4, Firmware versions tried: JWR66V and JWR66Y (both 4.3)

**Comment by mkubik** [comment]
I found some information that the camera might be causing this when gps coordinates are saved, so I switched that one off and it seemed to have helped stability. Can someone confirm this?

**Comment by mardaso** [comment]
Matthias,

Good find! 
I did hear about some BT issues on the Nexus 4 but not this one.
Is the App running stable now?

**Comment by mkubik** [comment]
Yes, no crash since I disabled saving coordinates in the camera app.

**Comment by mardaso** [comment]
Thanks for the feedback!
