### ISSUE TITLE
Does not discover BT device anymore

### ISSUE THREAD

**Issue by ik2wxx** [RHWorkshop/IR-Blue-Android#5]
Can't connect to device from Samsung S3 and LG Nexus 5, tried all latest versions of app.

**Comment by mardaso** [comment]
Sorry to hear that.
What's the version of Android you're on?
Did it work before? Or is this you're first try with IR-Blue?
Did you use fresh battery's? Just to rule out that the voltage is to low.

**Comment by ik2wxx** [comment]
Hello and thank you for reply.
Yes battery are new and I can see the device from my Mac (IR-Blue-DM) but not from Android devices.
Tried Nexus 5 with Android 6.0.1, S3 with Android 5.1.1
In the app, when I select "BT Connect", the device list is empty.

**Comment by mardaso** [comment]
You will need to pair the IR-Blue first in the Android Bluetooth settings menu.
And then they will show up in the BT connect list.

But I must say that I didn't try the app with a Android version above 4.
It can be that the Android device tries to connect through Bluetooth LE and not Bluetooth classic that the app supports. I will see if I can test it on a Nexus 7 tablet with a more recent Android version.
In the meanwhile you can try the above suggestions and try to pair first.

**Comment by mr23** [comment]
I hadn't tried my IR-Blue with my Samsung Note 4 (running 5.1.1) until now.
It does work. I did get a connect error the first time. But after 
restarting the app it connected.

**Comment by ik2wxx** [comment]
You're write, it just need to be connected manually before starting the App.
I'm sorry, I was using the iOS version before and did non know I should do that manually in Android.
